#!/bin/bash

echo "Installing Argon One Case Controls"

check_service() {

    srvstat=$(sudo systemctl status $1 2> /dev/null | grep "Loaded")

	if [ "$srvstat" == "" ]
    then
		echo 1
	else
		echo 0
	fi
}

check_package() {

    pkgstat=$(dpkg-query -W -f='${Status}\n' $1 2> /dev/null | grep "ok installed")

	if [ "$pkgstat" == "" ]
    then
		echo 1
	else
		echo 0
	fi
}

if [ $(check_service argond.service) == 0 ]
    then
        echo "Disable old argond.service"
        sudo systemctl stop argond.service
        sudo systemctl disable argond.service
fi

if [ $(check_service argononed.service) == 0 ]
    then
        echo "Disable old argononed.service"
        sudo systemctl stop argononed.service
        sudo systemctl disable argononed.service
fi

#packages=(raspi-gpio python3-rpi.gpio python3-smbus i2c-tools )
packages=(python3 python3-rpi.gpio python3-smbus python3-systemd)

for pkg in ${packages[@]}
    do
        if [ $(check_package $pkg) == 1 ]
        then
            sudo apt -y install $pkg
        fi

        if [ $(check_package $pkg) == 1 ]
        then
            echo "Er: Can not install $pkg"
            exit 1
        else
            echo "Ok: $pkg installed"
        fi
    done


echo "Create argon main daemon"

sudo cp argond.py /usr/bin/argond.py
sudo chown root:root /usr/bin/argond.py
sudo chmod 755 /usr/bin/argond.py

sudo cp argond.service /etc/systemd/system/argond.service
sudo chown root:root /etc/systemd/system/argond.service
sudo chmod 644 /etc/systemd/system/argond.service

sudo cp -n argond.conf /etc/argond.conf
sudo chown root:root /etc/argond.conf
sudo chmod 644 /etc/argond.conf

echo "Create argon shutdown daemon"

sudo cp argon-poweroff.py /usr/lib/systemd/system-shutdown/argon-poweroff.py
sudo chown root:root /usr/lib/systemd/system-shutdown/argon-poweroff.py
sudo chmod 755 /usr/lib/systemd/system-shutdown/argon-poweroff.py

echo "Create argon status viewer"

sudo cp argon-state.py /usr/bin/argon
sudo chown root:root /usr/bin/argon
sudo chmod 755 /usr/bin/argon

echo "Create argon remove script"

sudo cp argon-remove /usr/bin/argon-remove
sudo chown root:root /usr/bin/argon-remove
sudo chmod 755 /usr/bin/argon-remove

echo "Enable I2C bus"

sudo raspi-config nonint do_i2c 0

echo "Enable argon daeomon"

sudo systemctl daemon-reload
sudo systemctl enable argond.service
sudo systemctl start argond.service

echo "Finished!"
echo "Go to /etc/argond.conf to configure"